name = "rubikSolver"
uuid = "20175b8e-1943-4807-9260-7926bf8a8759"
authors = ["nkowne63rt <neutron63zf@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[targets]
test = ["Test", "Revise"]
